FROM node:16-alpine as build
WORKDIR /usr/src/app
COPY package.json .
COPY package-lock.json .
# COPY .npmrc .
RUN npm ci  --silent
COPY . .
RUN npm run build

# copy app files & run server
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
